[package]
name = "inference"
version = "0.1.0"
edition = "2024"

[dependencies]
kalosm = { git = "https://github.com/floneum/floneum.git", package = "kalosm", features = ["language", "cuda"] }
tokio = { version = "1.44.2", features = ["full"] }
